// Generated by ProtoGen, Version=2.4.1.555, Culture=neutral, PublicKeyToken=55f7125234beb589.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public static partial class MessageIdentify {

  #region Extension registration
  public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
  }
  #endregion
  #region Static variables
  #endregion
  #region Descriptor
  public static pbd::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbd::FileDescriptor descriptor;
  
  static MessageIdentify() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CiVzcmMvbWFpbi9wcm90by9tZXNzYWdlX2lkZW50aWZ5LnByb3RvKpoCCg9N", 
          "ZXNzYWdlUmVnaXN0cnkSGAoUQ0xJRU5UQ09NTU9OUkVTUE9OU0UQABIUChBV", 
          "U0VSTE9HSU5SRVFVRVNUEAESFQoRVVNFUkxPR0lOUkVTUE9OU0UQAhIVChFV", 
          "U0VSTE9HT1VUUkVRVUVTVBADEhYKElVTRVJMT0dPVVRSRVNQT05TRRAEEhsK", 
          "F0dFVENIQVJBQ1RFUklORk9SRVFVRVNUEAUSHAoYR0VUQ0hBUkFDVEVSSU5G", 
          "T1JFU1BPTlNFEAYSEQoNSVRFTU1PVkVFVkVOVBAHEhMKD0lURU1DUkFBVEVF", 
          "VkVOVBAIEhQKEElURU1ERVNUUk9ZRVZFTlQQCRIYChRDSEFSQUNURVJDUkVB", 
          "VEVFVkVOVBAKQigKDmNvbS5tbW8uc2VydmVyQhBNZXNzYWdlc0xvY2F0aW9u", 
        "iAEBoAEB"));
    pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
      descriptor = root;
      return null;
    };
    pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
        new pbd::FileDescriptor[] {
        }, assigner);
  }
  #endregion
  
}
#region Enums
public enum MessageRegistry {
  CLIENTCOMMONRESPONSE = 0,
  USERLOGINREQUEST = 1,
  USERLOGINRESPONSE = 2,
  USERLOGOUTREQUEST = 3,
  USERLOGOUTRESPONSE = 4,
  GETCHARACTERINFOREQUEST = 5,
  GETCHARACTERINFORESPONSE = 6,
  ITEMMOVEEVENT = 7,
  ITEMCRAATEEVENT = 8,
  ITEMDESTROYEVENT = 9,
  CHARACTERCREATEEVENT = 10,
}

#endregion


#endregion Designer generated code
