// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: world_server.proto

package com.mmo.server;

public final class ServerWorldProtocol {
  private ServerWorldProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserArrivedWorldRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserArrivedWorldRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string gateHost = 1;</code>
     */
    java.lang.String getGateHost();
    /**
     * <code>optional string gateHost = 1;</code>
     */
    com.google.protobuf.ByteString
        getGateHostBytes();

    /**
     * <code>optional int32 gatePort = 2;</code>
     */
    int getGatePort();

    /**
     * <code>optional int32 uid = 3;</code>
     */
    int getUid();

    /**
     * <code>optional int32 mapId = 4;</code>
     */
    int getMapId();
  }
  /**
   * Protobuf type {@code UserArrivedWorldRequest}
   */
  public  static final class UserArrivedWorldRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:UserArrivedWorldRequest)
      UserArrivedWorldRequestOrBuilder {
    // Use UserArrivedWorldRequest.newBuilder() to construct.
    private UserArrivedWorldRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private UserArrivedWorldRequest() {
      gateHost_ = "";
      gatePort_ = 0;
      uid_ = 0;
      mapId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UserArrivedWorldRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              gateHost_ = s;
              break;
            }
            case 16: {

              gatePort_ = input.readInt32();
              break;
            }
            case 24: {

              uid_ = input.readInt32();
              break;
            }
            case 32: {

              mapId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mmo.server.ServerWorldProtocol.internal_static_UserArrivedWorldRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mmo.server.ServerWorldProtocol.internal_static_UserArrivedWorldRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest.class, com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest.Builder.class);
    }

    public static final int GATEHOST_FIELD_NUMBER = 1;
    private volatile java.lang.Object gateHost_;
    /**
     * <code>optional string gateHost = 1;</code>
     */
    public java.lang.String getGateHost() {
      java.lang.Object ref = gateHost_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gateHost_ = s;
        return s;
      }
    }
    /**
     * <code>optional string gateHost = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGateHostBytes() {
      java.lang.Object ref = gateHost_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gateHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GATEPORT_FIELD_NUMBER = 2;
    private int gatePort_;
    /**
     * <code>optional int32 gatePort = 2;</code>
     */
    public int getGatePort() {
      return gatePort_;
    }

    public static final int UID_FIELD_NUMBER = 3;
    private int uid_;
    /**
     * <code>optional int32 uid = 3;</code>
     */
    public int getUid() {
      return uid_;
    }

    public static final int MAPID_FIELD_NUMBER = 4;
    private int mapId_;
    /**
     * <code>optional int32 mapId = 4;</code>
     */
    public int getMapId() {
      return mapId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getGateHostBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, gateHost_);
      }
      if (gatePort_ != 0) {
        output.writeInt32(2, gatePort_);
      }
      if (uid_ != 0) {
        output.writeInt32(3, uid_);
      }
      if (mapId_ != 0) {
        output.writeInt32(4, mapId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getGateHostBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, gateHost_);
      }
      if (gatePort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, gatePort_);
      }
      if (uid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, uid_);
      }
      if (mapId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, mapId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest)) {
        return super.equals(obj);
      }
      com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest other = (com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest) obj;

      boolean result = true;
      result = result && getGateHost()
          .equals(other.getGateHost());
      result = result && (getGatePort()
          == other.getGatePort());
      result = result && (getUid()
          == other.getUid());
      result = result && (getMapId()
          == other.getMapId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + GATEHOST_FIELD_NUMBER;
      hash = (53 * hash) + getGateHost().hashCode();
      hash = (37 * hash) + GATEPORT_FIELD_NUMBER;
      hash = (53 * hash) + getGatePort();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid();
      hash = (37 * hash) + MAPID_FIELD_NUMBER;
      hash = (53 * hash) + getMapId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserArrivedWorldRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserArrivedWorldRequest)
        com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mmo.server.ServerWorldProtocol.internal_static_UserArrivedWorldRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mmo.server.ServerWorldProtocol.internal_static_UserArrivedWorldRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest.class, com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest.Builder.class);
      }

      // Construct using com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        gateHost_ = "";

        gatePort_ = 0;

        uid_ = 0;

        mapId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mmo.server.ServerWorldProtocol.internal_static_UserArrivedWorldRequest_descriptor;
      }

      public com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest getDefaultInstanceForType() {
        return com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest.getDefaultInstance();
      }

      public com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest build() {
        com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest buildPartial() {
        com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest result = new com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest(this);
        result.gateHost_ = gateHost_;
        result.gatePort_ = gatePort_;
        result.uid_ = uid_;
        result.mapId_ = mapId_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest) {
          return mergeFrom((com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest other) {
        if (other == com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest.getDefaultInstance()) return this;
        if (!other.getGateHost().isEmpty()) {
          gateHost_ = other.gateHost_;
          onChanged();
        }
        if (other.getGatePort() != 0) {
          setGatePort(other.getGatePort());
        }
        if (other.getUid() != 0) {
          setUid(other.getUid());
        }
        if (other.getMapId() != 0) {
          setMapId(other.getMapId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object gateHost_ = "";
      /**
       * <code>optional string gateHost = 1;</code>
       */
      public java.lang.String getGateHost() {
        java.lang.Object ref = gateHost_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gateHost_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string gateHost = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGateHostBytes() {
        java.lang.Object ref = gateHost_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gateHost_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string gateHost = 1;</code>
       */
      public Builder setGateHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gateHost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string gateHost = 1;</code>
       */
      public Builder clearGateHost() {
        
        gateHost_ = getDefaultInstance().getGateHost();
        onChanged();
        return this;
      }
      /**
       * <code>optional string gateHost = 1;</code>
       */
      public Builder setGateHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gateHost_ = value;
        onChanged();
        return this;
      }

      private int gatePort_ ;
      /**
       * <code>optional int32 gatePort = 2;</code>
       */
      public int getGatePort() {
        return gatePort_;
      }
      /**
       * <code>optional int32 gatePort = 2;</code>
       */
      public Builder setGatePort(int value) {
        
        gatePort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 gatePort = 2;</code>
       */
      public Builder clearGatePort() {
        
        gatePort_ = 0;
        onChanged();
        return this;
      }

      private int uid_ ;
      /**
       * <code>optional int32 uid = 3;</code>
       */
      public int getUid() {
        return uid_;
      }
      /**
       * <code>optional int32 uid = 3;</code>
       */
      public Builder setUid(int value) {
        
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 uid = 3;</code>
       */
      public Builder clearUid() {
        
        uid_ = 0;
        onChanged();
        return this;
      }

      private int mapId_ ;
      /**
       * <code>optional int32 mapId = 4;</code>
       */
      public int getMapId() {
        return mapId_;
      }
      /**
       * <code>optional int32 mapId = 4;</code>
       */
      public Builder setMapId(int value) {
        
        mapId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 mapId = 4;</code>
       */
      public Builder clearMapId() {
        
        mapId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:UserArrivedWorldRequest)
    }

    // @@protoc_insertion_point(class_scope:UserArrivedWorldRequest)
    private static final com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest();
    }

    public static com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserArrivedWorldRequest>
        PARSER = new com.google.protobuf.AbstractParser<UserArrivedWorldRequest>() {
      public UserArrivedWorldRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UserArrivedWorldRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserArrivedWorldRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserArrivedWorldRequest> getParserForType() {
      return PARSER;
    }

    public com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  /**
   * Protobuf service {@code UserWorldService}
   */
  public static abstract class UserWorldService
      implements com.google.protobuf.Service {
    protected UserWorldService() {}

    public interface Interface {
      /**
       * <code>rpc userArrivedWorld(.UserArrivedWorldRequest) returns (.CommonResponse);</code>
       */
      public abstract void userArrivedWorld(
          com.google.protobuf.RpcController controller,
          com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest request,
          com.google.protobuf.RpcCallback<com.mmo.server.CommonProtocol.CommonResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new UserWorldService() {
        @java.lang.Override
        public  void userArrivedWorld(
            com.google.protobuf.RpcController controller,
            com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest request,
            com.google.protobuf.RpcCallback<com.mmo.server.CommonProtocol.CommonResponse> done) {
          impl.userArrivedWorld(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.userArrivedWorld(controller, (com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.mmo.server.CommonProtocol.CommonResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc userArrivedWorld(.UserArrivedWorldRequest) returns (.CommonResponse);</code>
     */
    public abstract void userArrivedWorld(
        com.google.protobuf.RpcController controller,
        com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest request,
        com.google.protobuf.RpcCallback<com.mmo.server.CommonProtocol.CommonResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.mmo.server.ServerWorldProtocol.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.userArrivedWorld(controller, (com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest)request,
            com.google.protobuf.RpcUtil.<com.mmo.server.CommonProtocol.CommonResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.mmo.server.CommonProtocol.CommonResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.mmo.server.ServerWorldProtocol.UserWorldService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void userArrivedWorld(
          com.google.protobuf.RpcController controller,
          com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest request,
          com.google.protobuf.RpcCallback<com.mmo.server.CommonProtocol.CommonResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.mmo.server.CommonProtocol.CommonResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.mmo.server.CommonProtocol.CommonResponse.class,
            com.mmo.server.CommonProtocol.CommonResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.mmo.server.CommonProtocol.CommonResponse userArrivedWorld(
          com.google.protobuf.RpcController controller,
          com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.mmo.server.CommonProtocol.CommonResponse userArrivedWorld(
          com.google.protobuf.RpcController controller,
          com.mmo.server.ServerWorldProtocol.UserArrivedWorldRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.mmo.server.CommonProtocol.CommonResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.mmo.server.CommonProtocol.CommonResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:UserWorldService)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserArrivedWorldRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserArrivedWorldRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022world_server.proto\032\014common.proto\"Y\n\027Us" +
      "erArrivedWorldRequest\022\020\n\010gateHost\030\001 \001(\t\022" +
      "\020\n\010gatePort\030\002 \001(\005\022\013\n\003uid\030\003 \001(\005\022\r\n\005mapId\030" +
      "\004 \001(\0052S\n\020UserWorldService\022?\n\020userArrived" +
      "World\022\030.UserArrivedWorldRequest\032\017.Common" +
      "Response\"\000B+\n\016com.mmo.serverB\023ServerWorl" +
      "dProtocol\210\001\001\240\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.mmo.server.CommonProtocol.getDescriptor(),
        }, assigner);
    internal_static_UserArrivedWorldRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserArrivedWorldRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UserArrivedWorldRequest_descriptor,
        new java.lang.String[] { "GateHost", "GatePort", "Uid", "MapId", });
    com.mmo.server.CommonProtocol.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
