// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: char_server.proto

package com.mmo.server;

public final class ServerCharacterProtocol {
  private ServerCharacterProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetCharacterRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetCharacterRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 uid = 1;</code>
     */
    int getUid();
  }
  /**
   * Protobuf type {@code GetCharacterRequest}
   */
  public  static final class GetCharacterRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:GetCharacterRequest)
      GetCharacterRequestOrBuilder {
    // Use GetCharacterRequest.newBuilder() to construct.
    private GetCharacterRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetCharacterRequest() {
      uid_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetCharacterRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              uid_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mmo.server.ServerCharacterProtocol.internal_static_GetCharacterRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mmo.server.ServerCharacterProtocol.internal_static_GetCharacterRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mmo.server.ServerCharacterProtocol.GetCharacterRequest.class, com.mmo.server.ServerCharacterProtocol.GetCharacterRequest.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private int uid_;
    /**
     * <code>optional int32 uid = 1;</code>
     */
    public int getUid() {
      return uid_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (uid_ != 0) {
        output.writeInt32(1, uid_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (uid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, uid_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mmo.server.ServerCharacterProtocol.GetCharacterRequest)) {
        return super.equals(obj);
      }
      com.mmo.server.ServerCharacterProtocol.GetCharacterRequest other = (com.mmo.server.ServerCharacterProtocol.GetCharacterRequest) obj;

      boolean result = true;
      result = result && (getUid()
          == other.getUid());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mmo.server.ServerCharacterProtocol.GetCharacterRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mmo.server.ServerCharacterProtocol.GetCharacterRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mmo.server.ServerCharacterProtocol.GetCharacterRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mmo.server.ServerCharacterProtocol.GetCharacterRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mmo.server.ServerCharacterProtocol.GetCharacterRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.mmo.server.ServerCharacterProtocol.GetCharacterRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mmo.server.ServerCharacterProtocol.GetCharacterRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mmo.server.ServerCharacterProtocol.GetCharacterRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mmo.server.ServerCharacterProtocol.GetCharacterRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.mmo.server.ServerCharacterProtocol.GetCharacterRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mmo.server.ServerCharacterProtocol.GetCharacterRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetCharacterRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetCharacterRequest)
        com.mmo.server.ServerCharacterProtocol.GetCharacterRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mmo.server.ServerCharacterProtocol.internal_static_GetCharacterRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mmo.server.ServerCharacterProtocol.internal_static_GetCharacterRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mmo.server.ServerCharacterProtocol.GetCharacterRequest.class, com.mmo.server.ServerCharacterProtocol.GetCharacterRequest.Builder.class);
      }

      // Construct using com.mmo.server.ServerCharacterProtocol.GetCharacterRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uid_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mmo.server.ServerCharacterProtocol.internal_static_GetCharacterRequest_descriptor;
      }

      public com.mmo.server.ServerCharacterProtocol.GetCharacterRequest getDefaultInstanceForType() {
        return com.mmo.server.ServerCharacterProtocol.GetCharacterRequest.getDefaultInstance();
      }

      public com.mmo.server.ServerCharacterProtocol.GetCharacterRequest build() {
        com.mmo.server.ServerCharacterProtocol.GetCharacterRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mmo.server.ServerCharacterProtocol.GetCharacterRequest buildPartial() {
        com.mmo.server.ServerCharacterProtocol.GetCharacterRequest result = new com.mmo.server.ServerCharacterProtocol.GetCharacterRequest(this);
        result.uid_ = uid_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mmo.server.ServerCharacterProtocol.GetCharacterRequest) {
          return mergeFrom((com.mmo.server.ServerCharacterProtocol.GetCharacterRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mmo.server.ServerCharacterProtocol.GetCharacterRequest other) {
        if (other == com.mmo.server.ServerCharacterProtocol.GetCharacterRequest.getDefaultInstance()) return this;
        if (other.getUid() != 0) {
          setUid(other.getUid());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mmo.server.ServerCharacterProtocol.GetCharacterRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mmo.server.ServerCharacterProtocol.GetCharacterRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int uid_ ;
      /**
       * <code>optional int32 uid = 1;</code>
       */
      public int getUid() {
        return uid_;
      }
      /**
       * <code>optional int32 uid = 1;</code>
       */
      public Builder setUid(int value) {
        
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 uid = 1;</code>
       */
      public Builder clearUid() {
        
        uid_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:GetCharacterRequest)
    }

    // @@protoc_insertion_point(class_scope:GetCharacterRequest)
    private static final com.mmo.server.ServerCharacterProtocol.GetCharacterRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mmo.server.ServerCharacterProtocol.GetCharacterRequest();
    }

    public static com.mmo.server.ServerCharacterProtocol.GetCharacterRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetCharacterRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetCharacterRequest>() {
      public GetCharacterRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetCharacterRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetCharacterRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetCharacterRequest> getParserForType() {
      return PARSER;
    }

    public com.mmo.server.ServerCharacterProtocol.GetCharacterRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetCharacterResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetCharacterResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .Character character = 1;</code>
     */
    boolean hasCharacter();
    /**
     * <code>optional .Character character = 1;</code>
     */
    com.mmo.server.CommonProtocol.Character getCharacter();
    /**
     * <code>optional .Character character = 1;</code>
     */
    com.mmo.server.CommonProtocol.CharacterOrBuilder getCharacterOrBuilder();
  }
  /**
   * Protobuf type {@code GetCharacterResponse}
   */
  public  static final class GetCharacterResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:GetCharacterResponse)
      GetCharacterResponseOrBuilder {
    // Use GetCharacterResponse.newBuilder() to construct.
    private GetCharacterResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetCharacterResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetCharacterResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.mmo.server.CommonProtocol.Character.Builder subBuilder = null;
              if (character_ != null) {
                subBuilder = character_.toBuilder();
              }
              character_ = input.readMessage(com.mmo.server.CommonProtocol.Character.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(character_);
                character_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mmo.server.ServerCharacterProtocol.internal_static_GetCharacterResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mmo.server.ServerCharacterProtocol.internal_static_GetCharacterResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mmo.server.ServerCharacterProtocol.GetCharacterResponse.class, com.mmo.server.ServerCharacterProtocol.GetCharacterResponse.Builder.class);
    }

    public static final int CHARACTER_FIELD_NUMBER = 1;
    private com.mmo.server.CommonProtocol.Character character_;
    /**
     * <code>optional .Character character = 1;</code>
     */
    public boolean hasCharacter() {
      return character_ != null;
    }
    /**
     * <code>optional .Character character = 1;</code>
     */
    public com.mmo.server.CommonProtocol.Character getCharacter() {
      return character_ == null ? com.mmo.server.CommonProtocol.Character.getDefaultInstance() : character_;
    }
    /**
     * <code>optional .Character character = 1;</code>
     */
    public com.mmo.server.CommonProtocol.CharacterOrBuilder getCharacterOrBuilder() {
      return getCharacter();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (character_ != null) {
        output.writeMessage(1, getCharacter());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (character_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCharacter());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mmo.server.ServerCharacterProtocol.GetCharacterResponse)) {
        return super.equals(obj);
      }
      com.mmo.server.ServerCharacterProtocol.GetCharacterResponse other = (com.mmo.server.ServerCharacterProtocol.GetCharacterResponse) obj;

      boolean result = true;
      result = result && (hasCharacter() == other.hasCharacter());
      if (hasCharacter()) {
        result = result && getCharacter()
            .equals(other.getCharacter());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasCharacter()) {
        hash = (37 * hash) + CHARACTER_FIELD_NUMBER;
        hash = (53 * hash) + getCharacter().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mmo.server.ServerCharacterProtocol.GetCharacterResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mmo.server.ServerCharacterProtocol.GetCharacterResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mmo.server.ServerCharacterProtocol.GetCharacterResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mmo.server.ServerCharacterProtocol.GetCharacterResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mmo.server.ServerCharacterProtocol.GetCharacterResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.mmo.server.ServerCharacterProtocol.GetCharacterResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mmo.server.ServerCharacterProtocol.GetCharacterResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mmo.server.ServerCharacterProtocol.GetCharacterResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mmo.server.ServerCharacterProtocol.GetCharacterResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.mmo.server.ServerCharacterProtocol.GetCharacterResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mmo.server.ServerCharacterProtocol.GetCharacterResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetCharacterResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetCharacterResponse)
        com.mmo.server.ServerCharacterProtocol.GetCharacterResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mmo.server.ServerCharacterProtocol.internal_static_GetCharacterResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mmo.server.ServerCharacterProtocol.internal_static_GetCharacterResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mmo.server.ServerCharacterProtocol.GetCharacterResponse.class, com.mmo.server.ServerCharacterProtocol.GetCharacterResponse.Builder.class);
      }

      // Construct using com.mmo.server.ServerCharacterProtocol.GetCharacterResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (characterBuilder_ == null) {
          character_ = null;
        } else {
          character_ = null;
          characterBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mmo.server.ServerCharacterProtocol.internal_static_GetCharacterResponse_descriptor;
      }

      public com.mmo.server.ServerCharacterProtocol.GetCharacterResponse getDefaultInstanceForType() {
        return com.mmo.server.ServerCharacterProtocol.GetCharacterResponse.getDefaultInstance();
      }

      public com.mmo.server.ServerCharacterProtocol.GetCharacterResponse build() {
        com.mmo.server.ServerCharacterProtocol.GetCharacterResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mmo.server.ServerCharacterProtocol.GetCharacterResponse buildPartial() {
        com.mmo.server.ServerCharacterProtocol.GetCharacterResponse result = new com.mmo.server.ServerCharacterProtocol.GetCharacterResponse(this);
        if (characterBuilder_ == null) {
          result.character_ = character_;
        } else {
          result.character_ = characterBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mmo.server.ServerCharacterProtocol.GetCharacterResponse) {
          return mergeFrom((com.mmo.server.ServerCharacterProtocol.GetCharacterResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mmo.server.ServerCharacterProtocol.GetCharacterResponse other) {
        if (other == com.mmo.server.ServerCharacterProtocol.GetCharacterResponse.getDefaultInstance()) return this;
        if (other.hasCharacter()) {
          mergeCharacter(other.getCharacter());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mmo.server.ServerCharacterProtocol.GetCharacterResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mmo.server.ServerCharacterProtocol.GetCharacterResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.mmo.server.CommonProtocol.Character character_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.mmo.server.CommonProtocol.Character, com.mmo.server.CommonProtocol.Character.Builder, com.mmo.server.CommonProtocol.CharacterOrBuilder> characterBuilder_;
      /**
       * <code>optional .Character character = 1;</code>
       */
      public boolean hasCharacter() {
        return characterBuilder_ != null || character_ != null;
      }
      /**
       * <code>optional .Character character = 1;</code>
       */
      public com.mmo.server.CommonProtocol.Character getCharacter() {
        if (characterBuilder_ == null) {
          return character_ == null ? com.mmo.server.CommonProtocol.Character.getDefaultInstance() : character_;
        } else {
          return characterBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Character character = 1;</code>
       */
      public Builder setCharacter(com.mmo.server.CommonProtocol.Character value) {
        if (characterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          character_ = value;
          onChanged();
        } else {
          characterBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .Character character = 1;</code>
       */
      public Builder setCharacter(
          com.mmo.server.CommonProtocol.Character.Builder builderForValue) {
        if (characterBuilder_ == null) {
          character_ = builderForValue.build();
          onChanged();
        } else {
          characterBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .Character character = 1;</code>
       */
      public Builder mergeCharacter(com.mmo.server.CommonProtocol.Character value) {
        if (characterBuilder_ == null) {
          if (character_ != null) {
            character_ =
              com.mmo.server.CommonProtocol.Character.newBuilder(character_).mergeFrom(value).buildPartial();
          } else {
            character_ = value;
          }
          onChanged();
        } else {
          characterBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .Character character = 1;</code>
       */
      public Builder clearCharacter() {
        if (characterBuilder_ == null) {
          character_ = null;
          onChanged();
        } else {
          character_ = null;
          characterBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .Character character = 1;</code>
       */
      public com.mmo.server.CommonProtocol.Character.Builder getCharacterBuilder() {
        
        onChanged();
        return getCharacterFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Character character = 1;</code>
       */
      public com.mmo.server.CommonProtocol.CharacterOrBuilder getCharacterOrBuilder() {
        if (characterBuilder_ != null) {
          return characterBuilder_.getMessageOrBuilder();
        } else {
          return character_ == null ?
              com.mmo.server.CommonProtocol.Character.getDefaultInstance() : character_;
        }
      }
      /**
       * <code>optional .Character character = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.mmo.server.CommonProtocol.Character, com.mmo.server.CommonProtocol.Character.Builder, com.mmo.server.CommonProtocol.CharacterOrBuilder> 
          getCharacterFieldBuilder() {
        if (characterBuilder_ == null) {
          characterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.mmo.server.CommonProtocol.Character, com.mmo.server.CommonProtocol.Character.Builder, com.mmo.server.CommonProtocol.CharacterOrBuilder>(
                  getCharacter(),
                  getParentForChildren(),
                  isClean());
          character_ = null;
        }
        return characterBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:GetCharacterResponse)
    }

    // @@protoc_insertion_point(class_scope:GetCharacterResponse)
    private static final com.mmo.server.ServerCharacterProtocol.GetCharacterResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mmo.server.ServerCharacterProtocol.GetCharacterResponse();
    }

    public static com.mmo.server.ServerCharacterProtocol.GetCharacterResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetCharacterResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetCharacterResponse>() {
      public GetCharacterResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetCharacterResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetCharacterResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetCharacterResponse> getParserForType() {
      return PARSER;
    }

    public com.mmo.server.ServerCharacterProtocol.GetCharacterResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  /**
   * Protobuf service {@code ServerCharacterService}
   */
  public static abstract class ServerCharacterService
      implements com.google.protobuf.Service {
    protected ServerCharacterService() {}

    public interface Interface {
      /**
       * <code>rpc GetCharacter(.GetCharacterRequest) returns (.GetCharacterResponse);</code>
       */
      public abstract void getCharacter(
          com.google.protobuf.RpcController controller,
          com.mmo.server.ServerCharacterProtocol.GetCharacterRequest request,
          com.google.protobuf.RpcCallback<com.mmo.server.ServerCharacterProtocol.GetCharacterResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new ServerCharacterService() {
        @java.lang.Override
        public  void getCharacter(
            com.google.protobuf.RpcController controller,
            com.mmo.server.ServerCharacterProtocol.GetCharacterRequest request,
            com.google.protobuf.RpcCallback<com.mmo.server.ServerCharacterProtocol.GetCharacterResponse> done) {
          impl.getCharacter(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getCharacter(controller, (com.mmo.server.ServerCharacterProtocol.GetCharacterRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.mmo.server.ServerCharacterProtocol.GetCharacterRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.mmo.server.ServerCharacterProtocol.GetCharacterResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc GetCharacter(.GetCharacterRequest) returns (.GetCharacterResponse);</code>
     */
    public abstract void getCharacter(
        com.google.protobuf.RpcController controller,
        com.mmo.server.ServerCharacterProtocol.GetCharacterRequest request,
        com.google.protobuf.RpcCallback<com.mmo.server.ServerCharacterProtocol.GetCharacterResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.mmo.server.ServerCharacterProtocol.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getCharacter(controller, (com.mmo.server.ServerCharacterProtocol.GetCharacterRequest)request,
            com.google.protobuf.RpcUtil.<com.mmo.server.ServerCharacterProtocol.GetCharacterResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.mmo.server.ServerCharacterProtocol.GetCharacterRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.mmo.server.ServerCharacterProtocol.GetCharacterResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.mmo.server.ServerCharacterProtocol.ServerCharacterService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getCharacter(
          com.google.protobuf.RpcController controller,
          com.mmo.server.ServerCharacterProtocol.GetCharacterRequest request,
          com.google.protobuf.RpcCallback<com.mmo.server.ServerCharacterProtocol.GetCharacterResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.mmo.server.ServerCharacterProtocol.GetCharacterResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.mmo.server.ServerCharacterProtocol.GetCharacterResponse.class,
            com.mmo.server.ServerCharacterProtocol.GetCharacterResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.mmo.server.ServerCharacterProtocol.GetCharacterResponse getCharacter(
          com.google.protobuf.RpcController controller,
          com.mmo.server.ServerCharacterProtocol.GetCharacterRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.mmo.server.ServerCharacterProtocol.GetCharacterResponse getCharacter(
          com.google.protobuf.RpcController controller,
          com.mmo.server.ServerCharacterProtocol.GetCharacterRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.mmo.server.ServerCharacterProtocol.GetCharacterResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.mmo.server.ServerCharacterProtocol.GetCharacterResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:ServerCharacterService)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCharacterRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetCharacterRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCharacterResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetCharacterResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021char_server.proto\032\014common.proto\"\"\n\023Get" +
      "CharacterRequest\022\013\n\003uid\030\001 \001(\005\"5\n\024GetChar" +
      "acterResponse\022\035\n\tcharacter\030\001 \001(\0132\n.Chara" +
      "cter2W\n\026ServerCharacterService\022=\n\014GetCha" +
      "racter\022\024.GetCharacterRequest\032\025.GetCharac" +
      "terResponse\"\000B/\n\016com.mmo.serverB\027ServerC" +
      "haracterProtocol\210\001\001\240\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.mmo.server.CommonProtocol.getDescriptor(),
        }, assigner);
    internal_static_GetCharacterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetCharacterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetCharacterRequest_descriptor,
        new java.lang.String[] { "Uid", });
    internal_static_GetCharacterResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetCharacterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetCharacterResponse_descriptor,
        new java.lang.String[] { "Character", });
    com.mmo.server.CommonProtocol.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
