// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/client_gate.proto

package com.mmo.server;

public final class ServerGateProtocol {
  private ServerGateProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code LoginCode}
   */
  public enum LoginCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OK = 0;</code>
     */
    OK(0),
    /**
     * <code>ERROR_PWD = 1;</code>
     */
    ERROR_PWD(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>OK = 0;</code>
     */
    public static final int OK_VALUE = 0;
    /**
     * <code>ERROR_PWD = 1;</code>
     */
    public static final int ERROR_PWD_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static LoginCode valueOf(int value) {
      return forNumber(value);
    }

    public static LoginCode forNumber(int value) {
      switch (value) {
        case 0: return OK;
        case 1: return ERROR_PWD;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LoginCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        LoginCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LoginCode>() {
            public LoginCode findValueByNumber(int number) {
              return LoginCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.mmo.server.ServerGateProtocol.getDescriptor().getEnumTypes().get(0);
    }

    private static final LoginCode[] VALUES = values();

    public static LoginCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private LoginCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:LoginCode)
  }

  public interface UserLoginRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserLoginRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string uname = 1;</code>
     */
    java.lang.String getUname();
    /**
     * <code>optional string uname = 1;</code>
     */
    com.google.protobuf.ByteString
        getUnameBytes();

    /**
     * <code>optional string upwd = 2;</code>
     */
    java.lang.String getUpwd();
    /**
     * <code>optional string upwd = 2;</code>
     */
    com.google.protobuf.ByteString
        getUpwdBytes();
  }
  /**
   * Protobuf type {@code UserLoginRequest}
   */
  public  static final class UserLoginRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:UserLoginRequest)
      UserLoginRequestOrBuilder {
    // Use UserLoginRequest.newBuilder() to construct.
    private UserLoginRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private UserLoginRequest() {
      uname_ = "";
      upwd_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UserLoginRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uname_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              upwd_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mmo.server.ServerGateProtocol.internal_static_UserLoginRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mmo.server.ServerGateProtocol.internal_static_UserLoginRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mmo.server.ServerGateProtocol.UserLoginRequest.class, com.mmo.server.ServerGateProtocol.UserLoginRequest.Builder.class);
    }

    public static final int UNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object uname_;
    /**
     * <code>optional string uname = 1;</code>
     */
    public java.lang.String getUname() {
      java.lang.Object ref = uname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uname_ = s;
        return s;
      }
    }
    /**
     * <code>optional string uname = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUnameBytes() {
      java.lang.Object ref = uname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UPWD_FIELD_NUMBER = 2;
    private volatile java.lang.Object upwd_;
    /**
     * <code>optional string upwd = 2;</code>
     */
    public java.lang.String getUpwd() {
      java.lang.Object ref = upwd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        upwd_ = s;
        return s;
      }
    }
    /**
     * <code>optional string upwd = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUpwdBytes() {
      java.lang.Object ref = upwd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        upwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUnameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, uname_);
      }
      if (!getUpwdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, upwd_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUnameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, uname_);
      }
      if (!getUpwdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, upwd_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mmo.server.ServerGateProtocol.UserLoginRequest)) {
        return super.equals(obj);
      }
      com.mmo.server.ServerGateProtocol.UserLoginRequest other = (com.mmo.server.ServerGateProtocol.UserLoginRequest) obj;

      boolean result = true;
      result = result && getUname()
          .equals(other.getUname());
      result = result && getUpwd()
          .equals(other.getUpwd());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + UNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUname().hashCode();
      hash = (37 * hash) + UPWD_FIELD_NUMBER;
      hash = (53 * hash) + getUpwd().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mmo.server.ServerGateProtocol.UserLoginRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mmo.server.ServerGateProtocol.UserLoginRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mmo.server.ServerGateProtocol.UserLoginRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mmo.server.ServerGateProtocol.UserLoginRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mmo.server.ServerGateProtocol.UserLoginRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.mmo.server.ServerGateProtocol.UserLoginRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mmo.server.ServerGateProtocol.UserLoginRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mmo.server.ServerGateProtocol.UserLoginRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mmo.server.ServerGateProtocol.UserLoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.mmo.server.ServerGateProtocol.UserLoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mmo.server.ServerGateProtocol.UserLoginRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserLoginRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserLoginRequest)
        com.mmo.server.ServerGateProtocol.UserLoginRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mmo.server.ServerGateProtocol.internal_static_UserLoginRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mmo.server.ServerGateProtocol.internal_static_UserLoginRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mmo.server.ServerGateProtocol.UserLoginRequest.class, com.mmo.server.ServerGateProtocol.UserLoginRequest.Builder.class);
      }

      // Construct using com.mmo.server.ServerGateProtocol.UserLoginRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uname_ = "";

        upwd_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mmo.server.ServerGateProtocol.internal_static_UserLoginRequest_descriptor;
      }

      public com.mmo.server.ServerGateProtocol.UserLoginRequest getDefaultInstanceForType() {
        return com.mmo.server.ServerGateProtocol.UserLoginRequest.getDefaultInstance();
      }

      public com.mmo.server.ServerGateProtocol.UserLoginRequest build() {
        com.mmo.server.ServerGateProtocol.UserLoginRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mmo.server.ServerGateProtocol.UserLoginRequest buildPartial() {
        com.mmo.server.ServerGateProtocol.UserLoginRequest result = new com.mmo.server.ServerGateProtocol.UserLoginRequest(this);
        result.uname_ = uname_;
        result.upwd_ = upwd_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mmo.server.ServerGateProtocol.UserLoginRequest) {
          return mergeFrom((com.mmo.server.ServerGateProtocol.UserLoginRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mmo.server.ServerGateProtocol.UserLoginRequest other) {
        if (other == com.mmo.server.ServerGateProtocol.UserLoginRequest.getDefaultInstance()) return this;
        if (!other.getUname().isEmpty()) {
          uname_ = other.uname_;
          onChanged();
        }
        if (!other.getUpwd().isEmpty()) {
          upwd_ = other.upwd_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mmo.server.ServerGateProtocol.UserLoginRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mmo.server.ServerGateProtocol.UserLoginRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object uname_ = "";
      /**
       * <code>optional string uname = 1;</code>
       */
      public java.lang.String getUname() {
        java.lang.Object ref = uname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string uname = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUnameBytes() {
        java.lang.Object ref = uname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string uname = 1;</code>
       */
      public Builder setUname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string uname = 1;</code>
       */
      public Builder clearUname() {
        
        uname_ = getDefaultInstance().getUname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string uname = 1;</code>
       */
      public Builder setUnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object upwd_ = "";
      /**
       * <code>optional string upwd = 2;</code>
       */
      public java.lang.String getUpwd() {
        java.lang.Object ref = upwd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          upwd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string upwd = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUpwdBytes() {
        java.lang.Object ref = upwd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          upwd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string upwd = 2;</code>
       */
      public Builder setUpwd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        upwd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string upwd = 2;</code>
       */
      public Builder clearUpwd() {
        
        upwd_ = getDefaultInstance().getUpwd();
        onChanged();
        return this;
      }
      /**
       * <code>optional string upwd = 2;</code>
       */
      public Builder setUpwdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        upwd_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:UserLoginRequest)
    }

    // @@protoc_insertion_point(class_scope:UserLoginRequest)
    private static final com.mmo.server.ServerGateProtocol.UserLoginRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mmo.server.ServerGateProtocol.UserLoginRequest();
    }

    public static com.mmo.server.ServerGateProtocol.UserLoginRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserLoginRequest>
        PARSER = new com.google.protobuf.AbstractParser<UserLoginRequest>() {
      public UserLoginRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UserLoginRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserLoginRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserLoginRequest> getParserForType() {
      return PARSER;
    }

    public com.mmo.server.ServerGateProtocol.UserLoginRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserLoginResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserLoginResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .LoginCode code = 1;</code>
     */
    int getCodeValue();
    /**
     * <code>optional .LoginCode code = 1;</code>
     */
    com.mmo.server.ServerGateProtocol.LoginCode getCode();

    /**
     * <code>optional string msAddr = 2;</code>
     */
    java.lang.String getMsAddr();
    /**
     * <code>optional string msAddr = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsAddrBytes();

    /**
     * <code>optional int64 port = 3;</code>
     */
    long getPort();
  }
  /**
   * Protobuf type {@code UserLoginResponse}
   */
  public  static final class UserLoginResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:UserLoginResponse)
      UserLoginResponseOrBuilder {
    // Use UserLoginResponse.newBuilder() to construct.
    private UserLoginResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private UserLoginResponse() {
      code_ = 0;
      msAddr_ = "";
      port_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UserLoginResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              code_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              msAddr_ = s;
              break;
            }
            case 24: {

              port_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mmo.server.ServerGateProtocol.internal_static_UserLoginResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mmo.server.ServerGateProtocol.internal_static_UserLoginResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mmo.server.ServerGateProtocol.UserLoginResponse.class, com.mmo.server.ServerGateProtocol.UserLoginResponse.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>optional .LoginCode code = 1;</code>
     */
    public int getCodeValue() {
      return code_;
    }
    /**
     * <code>optional .LoginCode code = 1;</code>
     */
    public com.mmo.server.ServerGateProtocol.LoginCode getCode() {
      com.mmo.server.ServerGateProtocol.LoginCode result = com.mmo.server.ServerGateProtocol.LoginCode.forNumber(code_);
      return result == null ? com.mmo.server.ServerGateProtocol.LoginCode.UNRECOGNIZED : result;
    }

    public static final int MSADDR_FIELD_NUMBER = 2;
    private volatile java.lang.Object msAddr_;
    /**
     * <code>optional string msAddr = 2;</code>
     */
    public java.lang.String getMsAddr() {
      java.lang.Object ref = msAddr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msAddr_ = s;
        return s;
      }
    }
    /**
     * <code>optional string msAddr = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsAddrBytes() {
      java.lang.Object ref = msAddr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 3;
    private long port_;
    /**
     * <code>optional int64 port = 3;</code>
     */
    public long getPort() {
      return port_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != com.mmo.server.ServerGateProtocol.LoginCode.OK.getNumber()) {
        output.writeEnum(1, code_);
      }
      if (!getMsAddrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, msAddr_);
      }
      if (port_ != 0L) {
        output.writeInt64(3, port_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != com.mmo.server.ServerGateProtocol.LoginCode.OK.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, code_);
      }
      if (!getMsAddrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, msAddr_);
      }
      if (port_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, port_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mmo.server.ServerGateProtocol.UserLoginResponse)) {
        return super.equals(obj);
      }
      com.mmo.server.ServerGateProtocol.UserLoginResponse other = (com.mmo.server.ServerGateProtocol.UserLoginResponse) obj;

      boolean result = true;
      result = result && code_ == other.code_;
      result = result && getMsAddr()
          .equals(other.getMsAddr());
      result = result && (getPort()
          == other.getPort());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + code_;
      hash = (37 * hash) + MSADDR_FIELD_NUMBER;
      hash = (53 * hash) + getMsAddr().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPort());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mmo.server.ServerGateProtocol.UserLoginResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mmo.server.ServerGateProtocol.UserLoginResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mmo.server.ServerGateProtocol.UserLoginResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mmo.server.ServerGateProtocol.UserLoginResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mmo.server.ServerGateProtocol.UserLoginResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.mmo.server.ServerGateProtocol.UserLoginResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mmo.server.ServerGateProtocol.UserLoginResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mmo.server.ServerGateProtocol.UserLoginResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mmo.server.ServerGateProtocol.UserLoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.mmo.server.ServerGateProtocol.UserLoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mmo.server.ServerGateProtocol.UserLoginResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserLoginResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserLoginResponse)
        com.mmo.server.ServerGateProtocol.UserLoginResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mmo.server.ServerGateProtocol.internal_static_UserLoginResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mmo.server.ServerGateProtocol.internal_static_UserLoginResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mmo.server.ServerGateProtocol.UserLoginResponse.class, com.mmo.server.ServerGateProtocol.UserLoginResponse.Builder.class);
      }

      // Construct using com.mmo.server.ServerGateProtocol.UserLoginResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        code_ = 0;

        msAddr_ = "";

        port_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mmo.server.ServerGateProtocol.internal_static_UserLoginResponse_descriptor;
      }

      public com.mmo.server.ServerGateProtocol.UserLoginResponse getDefaultInstanceForType() {
        return com.mmo.server.ServerGateProtocol.UserLoginResponse.getDefaultInstance();
      }

      public com.mmo.server.ServerGateProtocol.UserLoginResponse build() {
        com.mmo.server.ServerGateProtocol.UserLoginResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mmo.server.ServerGateProtocol.UserLoginResponse buildPartial() {
        com.mmo.server.ServerGateProtocol.UserLoginResponse result = new com.mmo.server.ServerGateProtocol.UserLoginResponse(this);
        result.code_ = code_;
        result.msAddr_ = msAddr_;
        result.port_ = port_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mmo.server.ServerGateProtocol.UserLoginResponse) {
          return mergeFrom((com.mmo.server.ServerGateProtocol.UserLoginResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mmo.server.ServerGateProtocol.UserLoginResponse other) {
        if (other == com.mmo.server.ServerGateProtocol.UserLoginResponse.getDefaultInstance()) return this;
        if (other.code_ != 0) {
          setCodeValue(other.getCodeValue());
        }
        if (!other.getMsAddr().isEmpty()) {
          msAddr_ = other.msAddr_;
          onChanged();
        }
        if (other.getPort() != 0L) {
          setPort(other.getPort());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mmo.server.ServerGateProtocol.UserLoginResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mmo.server.ServerGateProtocol.UserLoginResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ = 0;
      /**
       * <code>optional .LoginCode code = 1;</code>
       */
      public int getCodeValue() {
        return code_;
      }
      /**
       * <code>optional .LoginCode code = 1;</code>
       */
      public Builder setCodeValue(int value) {
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .LoginCode code = 1;</code>
       */
      public com.mmo.server.ServerGateProtocol.LoginCode getCode() {
        com.mmo.server.ServerGateProtocol.LoginCode result = com.mmo.server.ServerGateProtocol.LoginCode.forNumber(code_);
        return result == null ? com.mmo.server.ServerGateProtocol.LoginCode.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .LoginCode code = 1;</code>
       */
      public Builder setCode(com.mmo.server.ServerGateProtocol.LoginCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        code_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .LoginCode code = 1;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msAddr_ = "";
      /**
       * <code>optional string msAddr = 2;</code>
       */
      public java.lang.String getMsAddr() {
        java.lang.Object ref = msAddr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msAddr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msAddr = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsAddrBytes() {
        java.lang.Object ref = msAddr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msAddr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msAddr = 2;</code>
       */
      public Builder setMsAddr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msAddr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msAddr = 2;</code>
       */
      public Builder clearMsAddr() {
        
        msAddr_ = getDefaultInstance().getMsAddr();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msAddr = 2;</code>
       */
      public Builder setMsAddrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msAddr_ = value;
        onChanged();
        return this;
      }

      private long port_ ;
      /**
       * <code>optional int64 port = 3;</code>
       */
      public long getPort() {
        return port_;
      }
      /**
       * <code>optional int64 port = 3;</code>
       */
      public Builder setPort(long value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 port = 3;</code>
       */
      public Builder clearPort() {
        
        port_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:UserLoginResponse)
    }

    // @@protoc_insertion_point(class_scope:UserLoginResponse)
    private static final com.mmo.server.ServerGateProtocol.UserLoginResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mmo.server.ServerGateProtocol.UserLoginResponse();
    }

    public static com.mmo.server.ServerGateProtocol.UserLoginResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserLoginResponse>
        PARSER = new com.google.protobuf.AbstractParser<UserLoginResponse>() {
      public UserLoginResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UserLoginResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserLoginResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserLoginResponse> getParserForType() {
      return PARSER;
    }

    public com.mmo.server.ServerGateProtocol.UserLoginResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  /**
   * Protobuf service {@code ServerGateService}
   */
  public static abstract class ServerGateService
      implements com.google.protobuf.Service {
    protected ServerGateService() {}

    public interface Interface {
      /**
       * <code>rpc UserLogin(.UserLoginRequest) returns (.UserLoginResponse);</code>
       */
      public abstract void userLogin(
          com.google.protobuf.RpcController controller,
          com.mmo.server.ServerGateProtocol.UserLoginRequest request,
          com.google.protobuf.RpcCallback<com.mmo.server.ServerGateProtocol.UserLoginResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new ServerGateService() {
        @java.lang.Override
        public  void userLogin(
            com.google.protobuf.RpcController controller,
            com.mmo.server.ServerGateProtocol.UserLoginRequest request,
            com.google.protobuf.RpcCallback<com.mmo.server.ServerGateProtocol.UserLoginResponse> done) {
          impl.userLogin(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.userLogin(controller, (com.mmo.server.ServerGateProtocol.UserLoginRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.mmo.server.ServerGateProtocol.UserLoginRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.mmo.server.ServerGateProtocol.UserLoginResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc UserLogin(.UserLoginRequest) returns (.UserLoginResponse);</code>
     */
    public abstract void userLogin(
        com.google.protobuf.RpcController controller,
        com.mmo.server.ServerGateProtocol.UserLoginRequest request,
        com.google.protobuf.RpcCallback<com.mmo.server.ServerGateProtocol.UserLoginResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.mmo.server.ServerGateProtocol.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.userLogin(controller, (com.mmo.server.ServerGateProtocol.UserLoginRequest)request,
            com.google.protobuf.RpcUtil.<com.mmo.server.ServerGateProtocol.UserLoginResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.mmo.server.ServerGateProtocol.UserLoginRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.mmo.server.ServerGateProtocol.UserLoginResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.mmo.server.ServerGateProtocol.ServerGateService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void userLogin(
          com.google.protobuf.RpcController controller,
          com.mmo.server.ServerGateProtocol.UserLoginRequest request,
          com.google.protobuf.RpcCallback<com.mmo.server.ServerGateProtocol.UserLoginResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.mmo.server.ServerGateProtocol.UserLoginResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.mmo.server.ServerGateProtocol.UserLoginResponse.class,
            com.mmo.server.ServerGateProtocol.UserLoginResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.mmo.server.ServerGateProtocol.UserLoginResponse userLogin(
          com.google.protobuf.RpcController controller,
          com.mmo.server.ServerGateProtocol.UserLoginRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.mmo.server.ServerGateProtocol.UserLoginResponse userLogin(
          com.google.protobuf.RpcController controller,
          com.mmo.server.ServerGateProtocol.UserLoginRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.mmo.server.ServerGateProtocol.UserLoginResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.mmo.server.ServerGateProtocol.UserLoginResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:ServerGateService)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserLoginRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserLoginRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserLoginResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserLoginResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n src/main/proto/client_gate.proto\"/\n\020Us" +
      "erLoginRequest\022\r\n\005uname\030\001 \001(\t\022\014\n\004upwd\030\002 " +
      "\001(\t\"K\n\021UserLoginResponse\022\030\n\004code\030\001 \001(\0162\n" +
      ".LoginCode\022\016\n\006msAddr\030\002 \001(\t\022\014\n\004port\030\003 \001(\003" +
      "*\"\n\tLoginCode\022\006\n\002OK\020\000\022\r\n\tERROR_PWD\020\0012I\n\021" +
      "ServerGateService\0224\n\tUserLogin\022\021.UserLog" +
      "inRequest\032\022.UserLoginResponse\"\000B*\n\016com.m" +
      "mo.serverB\022ServerGateProtocol\210\001\001\240\001\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_UserLoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserLoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UserLoginRequest_descriptor,
        new java.lang.String[] { "Uname", "Upwd", });
    internal_static_UserLoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UserLoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UserLoginResponse_descriptor,
        new java.lang.String[] { "Code", "MsAddr", "Port", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
