// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gate_server.proto

package com.mmo.server;

public final class ServerGateProtocol {
  private ServerGateProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf service {@code EventDispatcher}
   */
  public static abstract class EventDispatcher
      implements com.google.protobuf.Service {
    protected EventDispatcher() {}

    public interface Interface {
      /**
       * <code>rpc moveEvent(.MoveEvent) returns (.CommonResponse);</code>
       */
      public abstract void moveEvent(
          com.google.protobuf.RpcController controller,
          com.mmo.server.CommonProtocol.MoveEvent request,
          com.google.protobuf.RpcCallback<com.mmo.server.CommonProtocol.CommonResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new EventDispatcher() {
        @java.lang.Override
        public  void moveEvent(
            com.google.protobuf.RpcController controller,
            com.mmo.server.CommonProtocol.MoveEvent request,
            com.google.protobuf.RpcCallback<com.mmo.server.CommonProtocol.CommonResponse> done) {
          impl.moveEvent(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.moveEvent(controller, (com.mmo.server.CommonProtocol.MoveEvent)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.mmo.server.CommonProtocol.MoveEvent.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.mmo.server.CommonProtocol.CommonResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc moveEvent(.MoveEvent) returns (.CommonResponse);</code>
     */
    public abstract void moveEvent(
        com.google.protobuf.RpcController controller,
        com.mmo.server.CommonProtocol.MoveEvent request,
        com.google.protobuf.RpcCallback<com.mmo.server.CommonProtocol.CommonResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.mmo.server.ServerGateProtocol.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.moveEvent(controller, (com.mmo.server.CommonProtocol.MoveEvent)request,
            com.google.protobuf.RpcUtil.<com.mmo.server.CommonProtocol.CommonResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.mmo.server.CommonProtocol.MoveEvent.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.mmo.server.CommonProtocol.CommonResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.mmo.server.ServerGateProtocol.EventDispatcher implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void moveEvent(
          com.google.protobuf.RpcController controller,
          com.mmo.server.CommonProtocol.MoveEvent request,
          com.google.protobuf.RpcCallback<com.mmo.server.CommonProtocol.CommonResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.mmo.server.CommonProtocol.CommonResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.mmo.server.CommonProtocol.CommonResponse.class,
            com.mmo.server.CommonProtocol.CommonResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.mmo.server.CommonProtocol.CommonResponse moveEvent(
          com.google.protobuf.RpcController controller,
          com.mmo.server.CommonProtocol.MoveEvent request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.mmo.server.CommonProtocol.CommonResponse moveEvent(
          com.google.protobuf.RpcController controller,
          com.mmo.server.CommonProtocol.MoveEvent request)
          throws com.google.protobuf.ServiceException {
        return (com.mmo.server.CommonProtocol.CommonResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.mmo.server.CommonProtocol.CommonResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:EventDispatcher)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021gate_server.proto\032\014common.proto2=\n\017Eve" +
      "ntDispatcher\022*\n\tmoveEvent\022\n.MoveEvent\032\017." +
      "CommonResponse\"\000B*\n\016com.mmo.serverB\022Serv" +
      "erGateProtocol\210\001\001\240\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.mmo.server.CommonProtocol.getDescriptor(),
        }, assigner);
    com.mmo.server.CommonProtocol.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
